version: '3'

services:
  gateway:
    container-name: gateway
    restart: always
    build: ./gateway
    ports:
      - '8000:8000'

  characters:
    container-name: characters
    restart: always
    build: ./characters
    ports:
      - ':8001'

  films:
    container-name: films
    restart: always
    build: ./films
    ports:
      - ':8002'

  planets:
    container-name: planets
    restart: always
    build: ./planets
    ports:
      - ':8003'

  database:
    container-name: database
    restart: always
    build: ./database
    ports:
      - ':8004'